name: Clone and Count Lines of Code

on:
  schedule:
    - cron: '25 11 * * *'

jobs:
  clone-and-count-loc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python development package
        run: sudo apt-get install python3-dev -y

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
